from sqlalchemy import Column, String, Boolean, Enum, ForeignKey, Date
from sqlalchemy.orm import relationship
from app.db.base_class import Base, UUIDMixin, TimestampMixin, SoftDeleteMixin
from app.schemas.enums import UserRole, VerificationStatus

class User(Base, UUIDMixin, TimestampMixin, SoftDeleteMixin):
    """
    Core authentication User model mapping email logins, Karachi coworker
    phone verifications, CNICs, roles, and profiles relations.
    """
    # lower case table name is automatically generated by base class as "user"
    email = Column(String(100), unique=True, index=True, nullable=True)
    hashed_password = Column(String(255), nullable=False)
    name = Column(String(100), nullable=False)
    mobile_number = Column(String(20), unique=True, index=True, nullable=False)
    office_name = Column(String(100), nullable=True)
    cnic_number = Column(String(20), unique=True, nullable=True)
    date_of_birth = Column(Date, nullable=True)
    
    role = Column(
        Enum(UserRole),
        default=UserRole.PASSENGER,
        nullable=False,
    )
    verification_status = Column(
        Enum(VerificationStatus),
        default=VerificationStatus.PENDING,
        nullable=False,
    )

    # Multi-profile relationships
    driver_profile = relationship(
        "DriverProfile",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",
    )
    passenger_profile = relationship(
        "PassengerProfile",
        back_populates="user",
        uselist=False,
        cascade="all, delete-orphan",
    )
    refresh_tokens = relationship(
        "RefreshToken",
        back_populates="user",
        cascade="all, delete-orphan",
    )


class DriverProfile(Base, UUIDMixin, TimestampMixin):
    """
    Profile extension model housing driver CNIC, licenses, verification status,
    and relationship to owned vehicles.
    """
    user_id = Column(
        ForeignKey("user.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )
    cnic_number = Column(String(20), unique=True, index=True, nullable=False)
    license_number = Column(String(50), unique=True, index=True, nullable=False)
    verification_status = Column(
        Enum(VerificationStatus),
        default=VerificationStatus.PENDING,
        nullable=False,
    )
    verification_notes = Column(String(255), nullable=True)

    user = relationship("User", back_populates="driver_profile")
    vehicles = relationship(
        "Vehicle",
        back_populates="driver_profile",
        cascade="all, delete-orphan",
    )


class PassengerProfile(Base, UUIDMixin, TimestampMixin):
    """
    Profile extension model housing passenger preferences and status configurations.
    """
    user_id = Column(
        ForeignKey("user.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )
    is_active = Column(Boolean, default=True, nullable=False)

    user = relationship("User", back_populates="passenger_profile")
