"""Initial schema setup with ratings and reviews

Revision ID: 06416e6f91c3
Revises: 
Create Date: 2026-07-23 11:42:51.650415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06416e6f91c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('office_name', sa.String(length=100), nullable=True),
    sa.Column('cnic_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('PASSENGER', 'DRIVER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_mobile_number'), ['mobile_number'], unique=True)

    op.create_table('driver_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cnic_number', sa.String(length=20), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verification_notes', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('driver_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_profile_cnic_number'), ['cnic_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_driver_profile_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_profile_license_number'), ['license_number'], unique=True)

    op.create_table('notification',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.Enum('RIDE', 'BOOKING', 'CHAT', 'SYSTEM', 'GENERAL', name='notificationcategory'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notificationpriority'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('passenger_profile',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('passenger_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_passenger_profile_id'), ['id'], unique=False)

    op.create_table('refresh_token',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_token_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_token_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_token_user_id'), ['user_id'], unique=False)

    op.create_table('vehicle',
    sa.Column('driver_profile_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('CAR', 'BIKE', name='vehicletype'), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('registration_number', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_driver_profile_id'), ['driver_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_registration_number'), ['registration_number'], unique=True)

    op.create_table('ride',
    sa.Column('driver_profile_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('pickup_area', sa.String(length=100), nullable=False),
    sa.Column('pickup_point', sa.String(length=255), nullable=False),
    sa.Column('destination_area', sa.String(length=100), nullable=False),
    sa.Column('destination_point', sa.String(length=255), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('fare_per_passenger', sa.Float(), nullable=False),
    sa.Column('ride_notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'FULL', 'COMPLETED', 'CANCELLED', name='ridestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_profile_id'], ['driver_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ride_departure_date'), ['departure_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_destination_area'), ['destination_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_driver_profile_id'), ['driver_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_pickup_area'), ['pickup_area'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('chat_room',
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_room_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_room_ride_id'), ['ride_id'], unique=True)

    op.create_table('rating',
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewee_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewee_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_reviewee_id'), ['reviewee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_ride_id'), ['ride_id'], unique=False)

    op.create_table('ride_request',
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ride_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ride_request_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_request_passenger_id'), ['passenger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_request_ride_id'), ['ride_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_request_status'), ['status'], unique=False)

    op.create_table('booking',
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=True),
    sa.Column('booking_status', sa.Enum('CONFIRMED', 'CANCELLED', 'COMPLETED', name='confirmedbookingstatus'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['passenger_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['ride_request.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_booking_status'), ['booking_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_passenger_id'), ['passenger_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_request_id'), ['request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_booking_ride_id'), ['ride_id'], unique=False)

    op.create_table('chat_message',
    sa.Column('chat_room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.Enum('TEXT', 'SYSTEM', 'RIDE_UPDATE', name='messagetype'), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_chat_room_id'), ['chat_room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_message_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_id'))
        batch_op.drop_index(batch_op.f('ix_chat_message_chat_room_id'))

    op.drop_table('chat_message')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_ride_id'))
        batch_op.drop_index(batch_op.f('ix_booking_request_id'))
        batch_op.drop_index(batch_op.f('ix_booking_passenger_id'))
        batch_op.drop_index(batch_op.f('ix_booking_id'))
        batch_op.drop_index(batch_op.f('ix_booking_booking_status'))

    op.drop_table('booking')
    with op.batch_alter_table('ride_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ride_request_status'))
        batch_op.drop_index(batch_op.f('ix_ride_request_ride_id'))
        batch_op.drop_index(batch_op.f('ix_ride_request_passenger_id'))
        batch_op.drop_index(batch_op.f('ix_ride_request_id'))

    op.drop_table('ride_request')
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_ride_id'))
        batch_op.drop_index(batch_op.f('ix_rating_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_rating_reviewee_id'))
        batch_op.drop_index(batch_op.f('ix_rating_id'))

    op.drop_table('rating')
    with op.batch_alter_table('chat_room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_room_ride_id'))
        batch_op.drop_index(batch_op.f('ix_chat_room_id'))

    op.drop_table('chat_room')
    with op.batch_alter_table('ride', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ride_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_ride_status'))
        batch_op.drop_index(batch_op.f('ix_ride_pickup_area'))
        batch_op.drop_index(batch_op.f('ix_ride_id'))
        batch_op.drop_index(batch_op.f('ix_ride_driver_profile_id'))
        batch_op.drop_index(batch_op.f('ix_ride_destination_area'))
        batch_op.drop_index(batch_op.f('ix_ride_departure_date'))

    op.drop_table('ride')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_registration_number'))
        batch_op.drop_index(batch_op.f('ix_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_vehicle_driver_profile_id'))

    op.drop_table('vehicle')
    with op.batch_alter_table('refresh_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_token_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_token'))
        batch_op.drop_index(batch_op.f('ix_refresh_token_id'))

    op.drop_table('refresh_token')
    with op.batch_alter_table('passenger_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_passenger_profile_id'))

    op.drop_table('passenger_profile')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_id'))

    op.drop_table('notification')
    with op.batch_alter_table('driver_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_profile_license_number'))
        batch_op.drop_index(batch_op.f('ix_driver_profile_id'))
        batch_op.drop_index(batch_op.f('ix_driver_profile_cnic_number'))

    op.drop_table('driver_profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_mobile_number'))
        batch_op.drop_index(batch_op.f('ix_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
