"""add notification_preference and other missing models

Revision ID: 59f4ad827ce7
Revises: 9d2748e75ad8
Create Date: 2026-07-25 20:47:52.558888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f4ad827ce7'
down_revision: Union[str, Sequence[str], None] = '9d2748e75ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preference',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ride_updates', sa.Boolean(), nullable=False),
    sa.Column('booking_updates', sa.Boolean(), nullable=False),
    sa.Column('chat_messages', sa.Boolean(), nullable=False),
    sa.Column('system_notifications', sa.Boolean(), nullable=False),
    sa.Column('marketing_notifications', sa.Boolean(), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('push_notifications', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_preference_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_preference_user_id'), ['user_id'], unique=True)

    op.create_table('push_subscription',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('subscription_data', sa.String(length=2000), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscription_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscription_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscription_user_id'), ['user_id'], unique=False)

    op.create_table('notification_delivery_log',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_delivery_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_delivery_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_delivery_log_notification_id'), ['notification_id'], unique=False)

    op.create_table('ride_tracking_session',
    sa.Column('ride_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_status', sa.Enum('PREPARING', 'DRIVER_EN_ROUTE', 'PASSENGER_PICKUP', 'RIDE_IN_PROGRESS', 'DESTINATION_APPROACHING', 'COMPLETED', 'CANCELLED', name='trackingstatus'), nullable=False),
    sa.Column('last_location_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('eta_minutes', sa.Float(), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('remaining_distance_km', sa.Float(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ride_tracking_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ride_tracking_session_current_status'), ['current_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_tracking_session_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_tracking_session_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ride_tracking_session_ride_id'), ['ride_id'], unique=True)

    op.create_table('message_read_status',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_read_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_read_status_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_read_status_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_read_status_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_to_message_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, 'chat_message', ['reply_to_message_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('data_json', sa.String(length=2000), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('data_json')
        batch_op.drop_column('action_url')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('edited_at')
        batch_op.drop_column('reply_to_message_id')

    with op.batch_alter_table('message_read_status', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_read_status_user_id'))
        batch_op.drop_index(batch_op.f('ix_message_read_status_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_read_status_id'))

    op.drop_table('message_read_status')
    with op.batch_alter_table('ride_tracking_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ride_tracking_session_ride_id'))
        batch_op.drop_index(batch_op.f('ix_ride_tracking_session_id'))
        batch_op.drop_index(batch_op.f('ix_ride_tracking_session_driver_id'))
        batch_op.drop_index(batch_op.f('ix_ride_tracking_session_current_status'))

    op.drop_table('ride_tracking_session')
    with op.batch_alter_table('notification_delivery_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_delivery_log_notification_id'))
        batch_op.drop_index(batch_op.f('ix_notification_delivery_log_id'))

    op.drop_table('notification_delivery_log')
    with op.batch_alter_table('push_subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscription_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscription_is_active'))
        batch_op.drop_index(batch_op.f('ix_push_subscription_id'))

    op.drop_table('push_subscription')
    with op.batch_alter_table('notification_preference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_preference_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_preference_id'))

    op.drop_table('notification_preference')
    # ### end Alembic commands ###
