from enum import Enum


class ErrorCode(str, Enum):
    """Centralized catalog of all enterprise error codes for RideMate API."""

    # Authentication
    AUTH_INVALID_CREDENTIALS = "AUTH_001"
    AUTH_TOKEN_EXPIRED = "AUTH_002"
    AUTH_TOKEN_REVOKED = "AUTH_003"
    AUTH_UNAUTHORIZED = "AUTH_004"
    AUTH_INVALID_TOKEN = "AUTH_005"

    # Users
    USER_NOT_FOUND = "USER_001"
    USER_DUPLICATE_MOBILE = "USER_002"
    USER_DUPLICATE_EMAIL = "USER_003"
    USER_WEAK_PASSWORD = "USER_004"

    # Drivers
    DRIVER_PROFILE_EXISTS = "DRIVER_001"
    DRIVER_DUPLICATE_CNIC = "DRIVER_002"
    DRIVER_DUPLICATE_LICENSE = "DRIVER_003"
    DRIVER_NOT_VERIFIED = "DRIVER_004"

    # Vehicles
    VEHICLE_NOT_FOUND = "VEHICLE_001"
    VEHICLE_DUPLICATE_REGISTRATION = "VEHICLE_002"
    VEHICLE_CANNOT_DELETE_ACTIVE = "VEHICLE_003"
    VEHICLE_SEAT_EXCEEDED = "VEHICLE_004"

    # Rides
    RIDE_DRIVER_HAS_ACTIVE = "RIDE_001"
    RIDE_NO_ACTIVE_VEHICLE = "RIDE_002"
    RIDE_DRIVER_UNVERIFIED = "RIDE_003"
    RIDE_PAST_DEPARTURE = "RIDE_004"
    RIDE_IMMUTABLE = "RIDE_005"
    RIDE_NOT_FOUND = "RIDE_006"

    # Bookings & Requests
    BOOKING_ACTIVE_CONSTRAINT = "BOOKING_001"
    BOOKING_OWN_RIDE_FORBIDDEN = "BOOKING_002"
    BOOKING_RIDE_FULL_OR_UNAVAILABLE = "BOOKING_003"
    BOOKING_UNAUTHORIZED_DRIVER = "BOOKING_004"
    BOOKING_INVALID_STATUS_TRANSITION = "BOOKING_005"
    BOOKING_NOT_FOUND = "BOOKING_006"

    # Chat
    CHAT_ROOM_INACTIVE_OR_EXPIRED = "CHAT_001"
    CHAT_ACCESS_DENIED = "CHAT_002"
    CHAT_ROOM_NOT_FOUND = "CHAT_003"

    # Notifications
    NOTIFICATION_NOT_FOUND = "NOTIF_001"

    # Ratings
    RATING_INVALID_SCORE = "RATING_001"
    RATING_SELF_FORBIDDEN = "RATING_002"
    RATING_RIDE_NOT_COMPLETED = "RATING_003"
    RATING_NOT_PARTICIPANT = "RATING_004"
    RATING_DUPLICATE_FORBIDDEN = "RATING_005"
    RATING_IMMUTABLE_AFTER_24H = "RATING_006"

    # System & Rate Limiting
    SYSTEM_INTERNAL_ERROR = "SYSTEM_001"
    SYSTEM_RATE_LIMIT_EXCEEDED = "SYSTEM_002"
    SYSTEM_SERVICE_UNAVAILABLE = "SYSTEM_003"
